### ISSUE TITLE
Reference implementation

### ISSUE THREAD

**Issue by mvdriel** [json-quiz/json-quiz#24]
Does there exist a reference implementation of a tool using this schema? Or a related database schema?

**Comment by stefk** [comment]
There's no reference implementation per se. The spec is currently used for data transfer, API validation and client-side representation of quizzes in the [claroline](https://github.com/claroline/Claroline) project. This is still a work in progress tough, and the underlying storage remains a legacy MySQL schema.

**Comment by mvdriel** [comment]
Thanks, I will check it out.
