### ISSUE TITLE
All types of question with scoring by result

### ISSUE THREAD

**Issue by Pauooo** [json-quiz/json-quiz#41]
All types of question should have a scoring by result : correct result = n points and wrong result = m points. This scoring come in addition to the scoring by answer.

**Comment by Elorfin** [comment]
IMO, you need to move this issue in claroline/Disctribution because the schema is already able to handle it. This is the application which can not create and use it.

**Comment by Pauooo** [comment]
Sorry :-( it's in Claroline/Distribution now
